# Generated by Django 3.0.7 on 2020-06-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subsidy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='制度名')),
                ('applicable_area', models.CharField(max_length=31, verbose_name='適用地域')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='開始日')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='終了日')),
                ('maximum_amount', models.CharField(blank=True, max_length=30, null=True, verbose_name='上限金額')),
                ('condition', models.TextField(blank=True, null=True, verbose_name='条件')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明文')),
                ('official_page', models.URLField(verbose_name='公式ページ')),
            ],
            options={
                'verbose_name': '支援金',
                'verbose_name_plural': '支援金',
            },
        ),
    ]

