# Generated by Django 3.0.7 on 2020-06-05 07:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name': '市区町村タグ',
                'verbose_name_plural': '市区町村タグ',
            },
        ),
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefecture', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name': '都道府県タグ',
                'verbose_name_plural': '都道府県タグ',
            },
        ),
        migrations.AddField(
            model_name='subsidy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='登録日'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subsidy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
        migrations.AddField(
            model_name='subsidy',
            name='city',
            field=models.ManyToManyField(blank=True, to='subsidy.City'),
        ),
        migrations.AddField(
            model_name='subsidy',
            name='prefectures',
            field=models.ManyToManyField(blank=True, to='subsidy.Prefecture'),
        ),
    ]
