# Generated by Django 3.0.7 on 2020-06-05 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0002_auto_20200605_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subsidy',
            old_name='city',
            new_name='citys',
        ),
    ]
