# Generated by Django 3.0.7 on 2020-06-05 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0003_auto_20200605_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subsidy',
            old_name='citys',
            new_name='cities',
        ),
    ]
