# Generated by Django 3.0.7 on 2020-06-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0006_auto_20200605_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(max_length=30, verbose_name='市区町村タグ'),
        ),
        migrations.AlterField(
            model_name='prefecture',
            name='prefecture',
            field=models.CharField(max_length=4, verbose_name='都道府県タグ'),
        ),
    ]
