# Generated by Django 3.0.3 on 2020-06-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0008_auto_20200605_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=30, verbose_name='テーマタグ')),
            ],
            options={
                'verbose_name': '04.テーマタグ',
                'verbose_name_plural': '04.テーマタグ',
            },
        ),
        migrations.RemoveField(
            model_name='subsidy',
            name='events',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.AddField(
            model_name='subsidy',
            name='themes',
            field=models.ManyToManyField(blank=True, to='subsidy.Theme', verbose_name='イベントタグ'),
        ),
    ]
