# Generated by Django 3.0.7 on 2020-06-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0009_auto_20200613_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidy',
            name='themes',
            field=models.ManyToManyField(blank=True, to='subsidy.Theme', verbose_name='テーマタグ'),
        ),
    ]
