# Generated by Django 3.0.3 on 2020-06-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0010_auto_20200613_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefecture',
            name='prefecture',
            field=models.CharField(max_length=10, verbose_name='都道府県タグ'),
        ),
    ]
