# Generated by Django 3.0.7 on 2020-06-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0011_auto_20200615_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='お名前')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='電話番号')),
                ('title', models.CharField(max_length=50, verbose_name='件名')),
                ('content', models.TextField(verbose_name='お問合せ内容')),
            ],
            options={
                'verbose_name': '05.お問合せ',
                'verbose_name_plural': '05.お問合せ',
            },
        ),
    ]
