# Generated by Django 3.0.7 on 2020-06-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0014_auto_20200617_0144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'verbose_name': '98.お問合せ', 'verbose_name_plural': '98.お問合せ'},
        ),
        migrations.AlterModelOptions(
            name='useralert',
            options={'verbose_name': '99.ユーザーアラート', 'verbose_name_plural': '99.ユーザーアラート'},
        ),
        migrations.AddField(
            model_name='useralert',
            name='other_note',
            field=models.TextField(blank=True, null=True, verbose_name='その他自由記載'),
        ),
        migrations.AlterField(
            model_name='useralert',
            name='problem_found',
            field=models.CharField(choices=[('1', 'URLのリンクが切れている'), ('2', '内容が誤っている'), ('3', 'その他')], max_length=100, verbose_name='問題'),
        ),
    ]
