# Generated by Django 3.0.7 on 2020-06-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0015_auto_20200617_0154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'verbose_name': '02.テーマタグ', 'verbose_name_plural': '02.テーマタグ'},
        ),
        migrations.RemoveField(
            model_name='subsidy',
            name='applicable_area',
        ),
        migrations.RemoveField(
            model_name='subsidy',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='subsidy',
            name='prefectures',
        ),
        migrations.AddField(
            model_name='subsidy',
            name='city',
            field=models.CharField(default='東京都23区', max_length=31, verbose_name='市区町村'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subsidy',
            name='prefecture',
            field=models.CharField(default='中央区', max_length=31, verbose_name='都道府県'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Prefecture',
        ),
    ]
