# Generated by Django 3.0.3 on 2020-06-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0016_auto_20200618_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='status',
            field=models.CharField(blank=True, choices=[('1', '未対応'), ('2', '対応中'), ('3', '完了')], max_length=100, null=True, verbose_name='対応ステータス'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
        migrations.AddField(
            model_name='useralert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
        migrations.AlterField(
            model_name='useralert',
            name='response_completed',
            field=models.CharField(blank=True, choices=[('1', '未対応'), ('2', '対応中'), ('3', '完了')], max_length=100, null=True, verbose_name='対応ステータス'),
        ),
    ]
