# Generated by Django 3.0.3 on 2020-06-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0017_auto_20200624_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidy',
            name='referrer',
            field=models.CharField(default='東京都江東区', max_length=30, verbose_name='参照元'),
            preserve_default=False,
        ),
    ]
