# Generated by Django 3.0.3 on 2020-07-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0018_auto_20200628_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidy',
            name='how_to_apply',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='利用・申請方法'),
        ),
        migrations.AddField(
            model_name='subsidy',
            name='overview',
            field=models.CharField(default='aa', max_length=100, verbose_name='制度の概要'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='condition',
            field=models.TextField(default='aa', max_length=3000, verbose_name='支給条件'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='description',
            field=models.TextField(default='aa', max_length=3000, verbose_name='支援内容'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='maximum_support_amount',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='上限金額'),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='prefecture',
            field=models.CharField(choices=[('1', '東京都23区')], max_length=31, verbose_name='都道府県'),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='referrer',
            field=models.CharField(max_length=30, verbose_name='お問合せ先'),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='support_amount_note',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='助成額'),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='target',
            field=models.CharField(choices=[('1', '個人向け'), ('2', '事業者向け')], default='個人向け', max_length=10, verbose_name='対象者'),
            preserve_default=False,
        ),
    ]
