# Generated by Django 3.0 on 2020-07-05 15:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0018_auto_20200628_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidy',
            name='how_to_apply',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='利用・申請方法'),
        ),
        migrations.AddField(
            model_name='subsidy',
            name='overview',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='制度の概要'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='city',
            field=models.CharField(max_length=13, verbose_name='市区町村'),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='condition',
            field=models.TextField(default=django.utils.timezone.now, max_length=3000, verbose_name='支給条件'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, max_length=1000, verbose_name='支援内容'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='maximum_support_amount',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='上限金額'),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='name',
            field=models.CharField(max_length=30, verbose_name='制度名'),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='prefecture',
            field=models.CharField(max_length=4, verbose_name='都道府県'),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='referrer',
            field=models.CharField(max_length=30, verbose_name='お問合せ先'),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='support_amount_note',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='助成額'),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='target',
            field=models.CharField(choices=[('1', '個人向け'), ('2', '事業者向け')], default=django.utils.timezone.now, max_length=10, verbose_name='対象者'),
            preserve_default=False,
        ),
    ]
