# Generated by Django 3.0.3 on 2020-07-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0019_auto_20200706_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidy',
            name='overview',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='制度の概要'),
        ),
    ]
