# Generated by Django 3.0 on 2020-07-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0019_auto_20200706_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidy',
            name='how_to_apply',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='利用・申請方法'),
        ),
    ]
