# Generated by Django 3.0 on 2020-07-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0020_auto_20200706_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidy',
            name='prefecture',
            field=models.CharField(choices=[('1', '東京都23区')], max_length=6, verbose_name='都道府県'),
        ),
    ]
