# Generated by Django 3.0.3 on 2020-07-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0020_auto_20200706_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidy',
            name='end_at',
            field=models.DateField(blank=True, null=True, verbose_name='終了日'),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='start_at',
            field=models.DateField(blank=True, null=True, verbose_name='開始日'),
        ),
    ]
