# Generated by Django 3.0.3 on 2020-07-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0021_auto_20200706_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidy',
            name='city',
            field=models.CharField(max_length=31, verbose_name='市区町村(ex.世田谷区)'),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='condition',
            field=models.TextField(max_length=1000, verbose_name='支給条件(1000字まで)'),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='description',
            field=models.TextField(max_length=3000, verbose_name='支援内容(3000字まで)'),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='how_to_apply',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='利用・申請方法(1000字まで)'),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='is_published',
            field=models.BooleanField(verbose_name='公開設定'),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='maximum_support_amount',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='上限金額(ex.10000)'),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='name',
            field=models.CharField(max_length=50, verbose_name='制度名(ex.移住支援制度)'),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='official_page',
            field=models.URLField(verbose_name='公式ページ(ex.https://aid-tree.com)'),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='overview',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='制度の概要(100字まで)'),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='prefecture',
            field=models.CharField(max_length=10, verbose_name='都道府県(ex.東京都)'),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='referrer',
            field=models.CharField(max_length=30, verbose_name='お問合せ先(ex.東京都世田谷区)'),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='support_amount_note',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='助成額(3000字まで)'),
        ),
    ]
