# Generated by Django 3.0.3 on 2020-07-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0022_auto_20200707_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidy',
            name='city',
            field=models.CharField(blank=True, max_length=31, null=True, verbose_name='市区町村(ex.世田谷区)'),
        ),
    ]
