# Generated by Django 3.0.3 on 2020-06-05 05:50

from django.db import migrations
import register.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', register.models.CustomUserManager()),
            ],
        ),
    ]
